/*   Here you can a add more data of elements   */
const elements = [{
        name: "Calcium",
        symbol: "Ca",
        atomicNumber: 20,
        radius: 197,
        meltingPoint: 839,
        boilingPoint: 1484,
        atomicWeight: 40.078,
        electronegativity: 1.91,
        oxidationStates: "+2",
        discoveryYear: "1808",
    },

    {
        name: "Nitrogen",
        symbol: "N",
        atomicNumber: 7,
        radius: 65,
        meltingPoint: -210,
        boilingPoint: -196,
        atomicWeight: 14.01,
        electronegativity: 3.04,
        oxidationStates: "-3, +3, +5",
        discoveryYear: "1772",
    }, {
        name: "Oxygen",
        symbol: "O",
        atomicNumber: 8,
        radius: 60,
        meltingPoint: -219,
        boilingPoint: -183,
        atomicWeight: 16.0,
        electronegativity: 3.44,
        oxidationStates: "-2",
        discoveryYear: "1774",
    }, {
        name: "Fluorine",
        symbol: "F",
        atomicNumber: 9,
        radius: 50,
        meltingPoint: -220,
        boilingPoint: -188,
        atomicWeight: 19.0,
        electronegativity: 3.98,
        oxidationStates: "-1",
        discoveryYear: "1670",
    },

    {
        name: "Neon",
        symbol: "Ne",
        atomicNumber: 10,
        radius: 38,
        meltingPoint: -249,
        boilingPoint: -246,
        atomicWeight: 20.18,
        electronegativity: null,
        oxidationStates: "0",
        discoveryYear: "1898",
    }, {
        name: "Sodium",
        symbol: "Na",
        atomicNumber: 11,
        radius: 180,
        meltingPoint: 98,
        boilingPoint: 883,
        atomicWeight: 22.99,
        electronegativity: 0.93,
        oxidationStates: "+1",
        discoveryYear: "1807",
    }, {
        name: "Magnesium",
        symbol: "Mg",
        atomicNumber: 12,
        radius: 150,
        meltingPoint: 650,
        boilingPoint: 1090,
        atomicWeight: 24.31,
        electronegativity: 1.31,
        oxidationStates: "+2",
        discoveryYear: "1755",
    },

    {
        name: "Aluminum",
        symbol: "Al",
        atomicNumber: 13,
        radius: 125,
        meltingPoint: 660,
        boilingPoint: 2467,
        atomicWeight: 26.98,
        electronegativity: 1.61,
        oxidationStates: "+3",
        discoveryYear: "1825",
    }, {
        name: "Silicon",
        symbol: "Si",
        atomicNumber: 14,
        radius: 110,
        meltingPoint: 1414,
        boilingPoint: 2900,
        atomicWeight: 28.09,
        electronegativity: 1.9,
        oxidationStates: "+4, -4",
        discoveryYear: "1824",
    }, {
        name: "Phosphorus",
        symbol: "P",
        atomicNumber: 15,
        radius: 100,
        meltingPoint: 44,
        boilingPoint: 280,
        atomicWeight: 30.97,
        electronegativity: 2.19,
        oxidationStates: "+5, -3",
        discoveryYear: "1669",
    },

    {
        name: "Sulfur",
        symbol: "S",
        atomicNumber: 16,
        radius: 100,
        meltingPoint: 115,
        boilingPoint: 444,
        atomicWeight: 32.06,
        electronegativity: 2.58,
        oxidationStates: "-2, +4, +6",
        discoveryYear: "Ancient",
    }, {
        name: "Chlorine",
        symbol: "Cl",
        atomicNumber: 17,
        radius: 100,
        meltingPoint: -101,
        boilingPoint: -34,
        atomicWeight: 35.45,
        electronegativity: 3.16,
        oxidationStates: "-1, +1, +3, +5, +7",
        discoveryYear: "1774",
    }, {
        name: "Potassium",
        symbol: "K",
        atomicNumber: 19,
        radius: 220,
        meltingPoint: 64,
        boilingPoint: 774,
        atomicWeight: 39.1,
        electronegativity: 0.82,
        oxidationStates: "+1",
        discoveryYear: "1807",
    },

    {
        name: "Argon",
        symbol: "Ar",
        atomicNumber: 18,
        radius: 71,
        meltingPoint: -189,
        boilingPoint: -186,
        atomicWeight: 39.95,
        electronegativity: null,
        oxidationStates: "0",
        discoveryYear: "1894",
    },

    {
        name: "Scandium",
        symbol: "Sc",
        atomicNumber: 21,
        radius: 162,
        meltingPoint: 1541,
        boilingPoint: 2836,
        atomicWeight: 44.96,
        electronegativity: 1.36,
        oxidationStates: "+3",
        discoveryYear: "1879",
    },

    {
        name: "Titanium",
        symbol: "Ti",
        atomicNumber: 22,
        radius: 147,
        meltingPoint: 1668,
        boilingPoint: 3287,
        atomicWeight: 47.87,
        electronegativity: 1.54,
        oxidationStates: "+2, +3, +4",
        discoveryYear: "1791",
    }, {
        name: "Vanadium",
        symbol: "V",
        atomicNumber: 23,
        radius: 134,
        meltingPoint: 1910,
        boilingPoint: 3407,
        atomicWeight: 50.94,
        electronegativity: 1.63,
        oxidationStates: "+2, +3, +4, +5",
        discoveryYear: "1801",
    }, {
        name: "Chromium",
        symbol: "Cr",
        atomicNumber: 24,
        radius: 128,
        meltingPoint: 1907,
        boilingPoint: 2671,
        atomicWeight: 52.0,
        electronegativity: 1.66,
        oxidationStates: "+2, +3, +6",
        discoveryYear: "1797",
    },

    {
        name: "Hydrogen",
        symbol: "H",
        atomicNumber: 1,
        radius: 25,
        meltingPoint: -259,
        boilingPoint: -253,
        atomicWeight: 1.008,
        electronegativity: 2.2,
        oxidationStates: "+1, -1",
        discoveryYear: "1766",
    }, {
        name: "Helium",
        symbol: "He",
        atomicNumber: 2,
        radius: 31,
        meltingPoint: -272,
        boilingPoint: -269,
        atomicWeight: 4.0026,
        electronegativity: null,
        oxidationStates: "0",
        discoveryYear: "1868",
    }, {
        name: "Lithium",
        symbol: "Li",
        atomicNumber: 3,
        radius: 145,
        meltingPoint: 180,
        boilingPoint: 1347,
        atomicWeight: 6.94,
        electronegativity: 0.98,
        oxidationStates: "+1",
        discoveryYear: "1817",
    },

    {
        name: "Iron",
        symbol: "Fe",
        atomicNumber: 26,
        radius: 126,
        meltingPoint: 1535,
        boilingPoint: 2750,
        atomicWeight: 55.845,
        electronegativity: 1.9,
        oxidationStates: "+2,(+3)",
        discoveryYear: "---",
    },

    {
        name: "Nickel",
        symbol: "Ni",
        atomicNumber: 28,
        radius: 124,
        meltingPoint: 1453,
        boilingPoint: 2732,
        atomicWeight: 58.69,
        electronegativity: 1.91,
        oxidationStates: "+2, +3",
        discoveryYear: "1751",
    }, {
        name: "Copper",
        symbol: "Cu",
        atomicNumber: 29,
        radius: 128,
        meltingPoint: 1084,
        boilingPoint: 2562,
        atomicWeight: 63.55,
        electronegativity: 1.9,
        oxidationStates: "+1, +2",
        discoveryYear: "Ancient",
    }, {
        name: "Zinc",
        symbol: "Zn",
        atomicNumber: 30,
        radius: 134,
        meltingPoint: 419,
        boilingPoint: 907,
        atomicWeight: 65.38,
        electronegativity: 1.65,
        oxidationStates: "+2",
        discoveryYear: "Ancient",
    },

    {
        name: "Gallium",
        symbol: "Ga",
        atomicNumber: 31,
        radius: 135,
        meltingPoint: 30,
        boilingPoint: 2403,
        atomicWeight: 69.72,
        electronegativity: 1.81,
        oxidationStates: "+3",
        discoveryYear: "1875",
    }, {
        name: "Germanium",
        symbol: "Ge",
        atomicNumber: 32,
        radius: 125,
        meltingPoint: 937,
        boilingPoint: 2830,
        atomicWeight: 72.63,
        electronegativity: 2.01,
        oxidationStates: "+4, -4",
        discoveryYear: "1886",
    }, {
        name: "Arsenic",
        symbol: "As",
        atomicNumber: 33,
        radius: 115,
        meltingPoint: 817,
        boilingPoint: 614,
        atomicWeight: 74.92,
        electronegativity: 2.18,
        oxidationStates: "+3, +5",
        discoveryYear: "Ancient",
    },

    {
        name: "Selenium",
        symbol: "Se",
        atomicNumber: 34,
        radius: 115,
        meltingPoint: 221,
        boilingPoint: 685,
        atomicWeight: 78.97,
        electronegativity: 2.55,
        oxidationStates: "-2, +4, +6",
        discoveryYear: "1817",
    }, {
        name: "Bromine",
        symbol: "Br",
        atomicNumber: 35,
        radius: 115,
        meltingPoint: -7,
        boilingPoint: 59,
        atomicWeight: 79.9,
        electronegativity: 2.96,
        oxidationStates: "-1, +1, +3, +5, +7",
        discoveryYear: "1826",
    }, {
        name: "Krypton",
        symbol: "Kr",
        atomicNumber: 36,
        radius: 88,
        meltingPoint: -157,
        boilingPoint: -153,
        atomicWeight: 83.8,
        electronegativity: null,
        oxidationStates: "0",
        discoveryYear: "1898",
    },

    {
        name: "Rubidium",
        symbol: "Rb",
        atomicNumber: 37,
        radius: 235,
        meltingPoint: 39,
        boilingPoint: 688,
        atomicWeight: 85.47,
        electronegativity: 0.82,
        oxidationStates: "+1",
        discoveryYear: "1861",
    }, {
        name: "Strontium",
        symbol: "Sr",
        atomicNumber: 38,
        radius: 200,
        meltingPoint: 769,
        boilingPoint: 1384,
        atomicWeight: 87.62,
        electronegativity: 0.95,
        oxidationStates: "+2",
        discoveryYear: "1790",
    }, {
        name: "Yttrium",
        symbol: "Y",
        atomicNumber: 39,
        radius: 180,
        meltingPoint: 1526,
        boilingPoint: 3345,
        atomicWeight: 88.91,
        electronegativity: 1.22,
        oxidationStates: "+3",
        discoveryYear: "1794",
    },

    {
        name: "Zirconium",
        symbol: "Zr",
        atomicNumber: 40,
        radius: 160,
        meltingPoint: 1855,
        boilingPoint: 4409,
        atomicWeight: 91.22,
        electronegativity: 1.33,
        oxidationStates: "+4",
        discoveryYear: "1789",
    }, {
        name: "Niobium",
        symbol: "Nb",
        atomicNumber: 41,
        radius: 145,
        meltingPoint: 2477,
        boilingPoint: 4744,
        atomicWeight: 92.91,
        electronegativity: 1.6,
        oxidationStates: "-1, +2, +3, +4, +5",
        discoveryYear: "1801",
    }, {
        name: "Molybdenum",
        symbol: "Mo",
        atomicNumber: 42,
        radius: 139,
        meltingPoint: 2623,
        boilingPoint: 4639,
        atomicWeight: 95.95,
        electronegativity: 2.16,
        oxidationStates: "-2, +2, +3, +4, +5, +6",
        discoveryYear: "1778",
    },

    {
        name: "Palladium",
        symbol: "Pd",
        atomicNumber: 46,
        radius: 131,
        meltingPoint: 1554,
        boilingPoint: 2963,
        atomicWeight: 106.42,
        electronegativity: 2.2,
        oxidationStates: "+2, +4",
        discoveryYear: "1803",
    }, {
        name: "Silver",
        symbol: "Ag",
        atomicNumber: 47,
        radius: 153,
        meltingPoint: 961,
        boilingPoint: 2212,
        atomicWeight: 107.87,
        electronegativity: 1.93,
        oxidationStates: "+1",
        discoveryYear: "Ancient",
    }, {
        name: "Cadmium",
        symbol: "Cd",
        atomicNumber: 48,
        radius: 148,
        meltingPoint: 321,
        boilingPoint: 765,
        atomicWeight: 112.41,
        electronegativity: 1.69,
        oxidationStates: "+2",
        discoveryYear: "1817",
    },

    {
        name: "Gold",
        symbol: "Au",
        atomicNumber: 79,
        radius: 144,
        meltingPoint: 1064,
        boilingPoint: 2807,
        atomicWeight: 196.967,
        electronegativity: 2.54,
        oxidationStates: "+1, +3",
        discoveryYear: "3000 B.C",
    },

    {
        name: "Carbon",
        symbol: "C",
        atomicNumber: 6,
        radius: 77.2,
        meltingPoint: 3500,
        boilingPoint: 4827,
        atomicWeight: 12.011,
        electronegativity: 2.55,
        oxidationStates: "(-4),+2(+4)",
        discoveryYear: "----",
    },
];

/*oooooooooooooiiiiooooooooooooooooooooooooo*/

function science() {
    var input = document.getElementById("valueput").value.toLowerCase();

    for (let i = 0; i < elements.length; i++) {
        if (elements[i].name.toLowerCase() === input) {
            document.getElementById("box1").innerHTML =
                elements[i].atomicNumber;
            document.getElementById("box2").innerHTML = elements[i].radius;
            document.getElementById("box3").innerHTML =
                elements[i].meltingPoint;
            document.getElementById("box4").innerHTML =
                elements[i].boilingPoint;
            document.getElementById("middle1").innerHTML = elements[i].symbol;
            document.getElementById("box5").innerHTML =
                elements[i].atomicWeight;
            document.getElementById("box6").innerHTML =
                elements[i].electronegativity;
            document.getElementById("box7").innerHTML =
                elements[i].oxidationStates;
            document.getElementById("box8").innerHTML =
                elements[i].discoveryYear;
            break;
        }
    }
}